name: CI
on:
    push:

concurrency: investager

env:
    REGISTRY: ghcr.io

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            packages: write
        outputs:
            ui-affected: ${{ steps.ui-affected.outputs.ui-affected }}
            api-affected: ${{ steps.api-affected.outputs.api-affected }}
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - uses: nrwl/nx-set-shas@v3
            - run: npm ci

            - run: npx nx workspace-lint
            - run: npx nx format:check
            - run: npx nx affected --target=lint --parallel=3
            - run: npx nx affected --target=test --parallel=3 --ci --code-coverage
            - run: npx nx affected --target=build --parallel=3

            - name: Log in to the Container registry
              if: github.ref == 'refs/heads/main'
              uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - id: ui-affected
              run: if test -d dist/apps/ui; then echo "ui-affected=true" >> $GITHUB_OUTPUT; else echo "ui-affected=false" >> $GITHUB_OUTPUT; fi
            - name: Extract UI metadata (tags, labels) for Docker
              if: ${{ steps.ui-affected.outputs.ui-affected == 'true' && github.ref == 'refs/heads/main' }}
              id: meta-ui
              uses: docker/metadata-action@507c2f2dc502c992ad446e3d7a5dfbe311567a96
              with:
                  images: ${{ env.REGISTRY }}/${{ github.repository }}/ui
                  tags: |
                      type=sha
            - name: Make and push UI
              if: ${{ steps.ui-affected.outputs.ui-affected == 'true' && github.ref == 'refs/heads/main' }}
              uses: docker/build-push-action@37abcedcc1da61a57767b7588cb9d03eb57e28b3
              with:
                  context: .
                  file: apps/ui/Dockerfile.dockerfile
                  push: true
                  tags: ${{ steps.meta-ui.outputs.tags }}
                  labels: ${{ steps.meta-ui.outputs.labels }}

            - id: api-affected
              run: if test -d dist/apps/api; then echo "api-affected=true" >> $GITHUB_OUTPUT; else echo "api-affected=false" >> $GITHUB_OUTPUT; fi
            - name: Extract API metadata (tags, labels) for Docker
              if: ${{ steps.api-affected.outputs.api-affected == 'true' && github.ref == 'refs/heads/main' }}
              id: meta-api
              uses: docker/metadata-action@507c2f2dc502c992ad446e3d7a5dfbe311567a96
              with:
                  images: ${{ env.REGISTRY }}/${{ github.repository }}/api
                  tags: |
                      type=sha
            - name: Make and push API
              if: ${{ steps.api-affected.outputs.api-affected == 'true' && github.ref == 'refs/heads/main' }}
              uses: docker/build-push-action@37abcedcc1da61a57767b7588cb9d03eb57e28b3
              with:
                  context: .
                  file: apps/api/Dockerfile.dockerfile
                  push: true
                  tags: ${{ steps.meta-api.outputs.tags }}
                  labels: ${{ steps.meta-api.outputs.labels }}
