name: CI
on:
    push:
concurrency: investager
jobs:
    build:
        runs-on: ubuntu-latest
        outputs:
            ui-affected: ${{ steps.ui-affected.outputs.ui-affected }}
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - uses: nrwl/nx-set-shas@v3
            - run: npm ci

            - run: npx nx workspace-lint
            - run: npx nx format:check
            - run: npx nx affected --target=lint --parallel=3
            - run: npx nx affected --target=test --parallel=3 --ci --code-coverage
            - run: npx nx affected --target=build --parallel=3

            - id: ui-affected
              run: if test -d dist/apps/ui; then echo "ui-affected=true" >> $GITHUB_OUTPUT; else echo "ui-affected=false" >> $GITHUB_OUTPUT; fi

            - name: Zip UI
              if: ${{ steps.ui-affected.outputs.ui-affected == 'true' }}
              run: (cd dist/apps/ui && zip -r ui.zip .)

            - name: Upload
              if: ${{ steps.ui-affected.outputs.ui-affected == 'true' }}
              uses: actions/upload-artifact@v3
              with:
                  name: ui
                  path: dist/apps/ui/ui.zip
    deploy-ui:
        if: github.ref == 'refs/heads/main'
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Get artifact
              if: ${{ needs.build.outputs.ui-affected == 'true' }}
              uses: actions/download-artifact@v3
              with:
                  name: ui
            - name: Copy artifact
              if: ${{ needs.build.outputs.ui-affected == 'true' }}
              uses: appleboy/scp-action@master
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  key: ${{ secrets.KEY }}
                  source: 'ui.zip'
                  target: '/home/ubuntu'
            - name: Upgrade
              if: ${{ needs.build.outputs.ui-affected == 'true' }}
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  key: ${{ secrets.KEY }}
                  script: |
                      cd /home/ubuntu
                      zip -r "$(date +%Y%m%d_%H%M%S)_ui.zip" ui/
                      rm -rf ui
                      unzip ui.zip -d ui
                      rm ui.zip
